#include <stdio.h>

void AAssetDir_close() { printf("STUB: AAssetDir_close called\n"); }
void AAssetManager_fromJava() { printf("STUB: AAssetManager_fromJava called\n"); }
void AAssetManager_open() { printf("STUB: AAssetManager_open called\n"); }
void AAssetManager_openDir() { printf("STUB: AAssetManager_openDir called\n"); }
void AAsset_close() { printf("STUB: AAsset_close called\n"); }
void AAsset_getLength() { printf("STUB: AAsset_getLength called\n"); }
void AAsset_read() { printf("STUB: AAsset_read called\n"); }
void AAsset_seek() { printf("STUB: AAsset_seek called\n"); }
void ALooper_acquire() { printf("STUB: ALooper_acquire called\n"); }
void ALooper_forThread() { printf("STUB: ALooper_forThread called\n"); }
void ALooper_pollAll() { printf("STUB: ALooper_pollAll called\n"); }
void ALooper_prepare() { printf("STUB: ALooper_prepare called\n"); }
void ALooper_release() { printf("STUB: ALooper_release called\n"); }
void ALooper_wake() { printf("STUB: ALooper_wake called\n"); }
void ANativeWindow_acquire() { printf("STUB: ANativeWindow_acquire called\n"); }
void ANativeWindow_fromSurface() { printf("STUB: ANativeWindow_fromSurface called\n"); }
void ANativeWindow_getHeight() { printf("STUB: ANativeWindow_getHeight called\n"); }
void ANativeWindow_getWidth() { printf("STUB: ANativeWindow_getWidth called\n"); }
void ANativeWindow_release() { printf("STUB: ANativeWindow_release called\n"); }
void ANativeWindow_setBuffersGeometry() { printf("STUB: ANativeWindow_setBuffersGeometry called\n"); }
void ASensorEventQueue_disableSensor() { printf("STUB: ASensorEventQueue_disableSensor called\n"); }
void ASensorEventQueue_enableSensor() { printf("STUB: ASensorEventQueue_enableSensor called\n"); }
void ASensorEventQueue_getEvents() { printf("STUB: ASensorEventQueue_getEvents called\n"); }
void ASensorEventQueue_hasEvents() { printf("STUB: ASensorEventQueue_hasEvents called\n"); }
void ASensorEventQueue_setEventRate() { printf("STUB: ASensorEventQueue_setEventRate called\n"); }
void ASensorManager_createEventQueue() { printf("STUB: ASensorManager_createEventQueue called\n"); }
void ASensorManager_destroyEventQueue() { printf("STUB: ASensorManager_destroyEventQueue called\n"); }
void ASensorManager_getDefaultSensor() { printf("STUB: ASensorManager_getDefaultSensor called\n"); }
void ASensorManager_getInstance() { printf("STUB: ASensorManager_getInstance called\n"); }
void ASensorManager_getSensorList() { printf("STUB: ASensorManager_getSensorList called\n"); }
void ASensor_getMinDelay() { printf("STUB: ASensor_getMinDelay called\n"); }
void ASensor_getName() { printf("STUB: ASensor_getName called\n"); }
void ASensor_getResolution() { printf("STUB: ASensor_getResolution called\n"); }
void ASensor_getType() { printf("STUB: ASensor_getType called\n"); }
void ASensor_getVendor() { printf("STUB: ASensor_getVendor called\n"); }
void SL_IID_ANDROIDCONFIGURATION() { printf("STUB: SL_IID_ANDROIDCONFIGURATION called\n"); }
void SL_IID_BUFFERQUEUE() { printf("STUB: SL_IID_BUFFERQUEUE called\n"); }
void SL_IID_ENGINE() { printf("STUB: SL_IID_ENGINE called\n"); }
void SL_IID_PLAY() { printf("STUB: SL_IID_PLAY called\n"); }
void __FD_ISSET_chk() { printf("STUB: __FD_ISSET_chk called\n"); }
void __FD_SET_chk() { printf("STUB: __FD_SET_chk called\n"); }
void __android_log_print() { printf("STUB: __android_log_print called\n"); }
void __android_log_vprint() { printf("STUB: __android_log_vprint called\n"); }
void __android_log_write() { printf("STUB: __android_log_write called\n"); }
void __ctype_get_mb_cur_max() { printf("STUB: __ctype_get_mb_cur_max called\n"); }
void __cxa_atexit() { printf("STUB: __cxa_atexit called\n"); }
void __cxa_finalize() { printf("STUB: __cxa_finalize called\n"); }
void __errno() { printf("STUB: __errno called\n"); }
void __memcpy_chk() { printf("STUB: __memcpy_chk called\n"); }
void __memmove_chk() { printf("STUB: __memmove_chk called\n"); }
void __sF() { printf("STUB: __sF called\n"); }
void __stack_chk_fail() { printf("STUB: __stack_chk_fail called\n"); }
void __strcat_chk() { printf("STUB: __strcat_chk called\n"); }
void __strcpy_chk() { printf("STUB: __strcpy_chk called\n"); }
void __strlen_chk() { printf("STUB: __strlen_chk called\n"); }
void __strncat_chk() { printf("STUB: __strncat_chk called\n"); }
void __strncpy_chk() { printf("STUB: __strncpy_chk called\n"); }
void __strncpy_chk2() { printf("STUB: __strncpy_chk2 called\n"); }
void __system_property_find() { printf("STUB: __system_property_find called\n"); }
void __system_property_get() { printf("STUB: __system_property_get called\n"); }
void __system_property_read() { printf("STUB: __system_property_read called\n"); }
void __umask_chk() { printf("STUB: __umask_chk called\n"); }
void __vsnprintf_chk() { printf("STUB: __vsnprintf_chk called\n"); }
void __vsprintf_chk() { printf("STUB: __vsprintf_chk called\n"); }
void accept() { printf("STUB: accept called\n"); }
void access() { printf("STUB: access called\n"); }
void android_set_abort_message() { printf("STUB: android_set_abort_message called\n"); }
void atoi() { printf("STUB: atoi called\n"); }
void atol() { printf("STUB: atol called\n"); }
void basename() { printf("STUB: basename called\n"); }
void bind() { printf("STUB: bind called\n"); }
void bsearch() { printf("STUB: bsearch called\n"); }
void btowc() { printf("STUB: btowc called\n"); }
void chmod() { printf("STUB: chmod called\n"); }
void clock() { printf("STUB: clock called\n"); }
void clock_getres() { printf("STUB: clock_getres called\n"); }
void clock_gettime() { printf("STUB: clock_gettime called\n"); }
void close() { printf("STUB: close called\n"); }
void closedir() { printf("STUB: closedir called\n"); }
void closelog() { printf("STUB: closelog called\n"); }
void connect() { printf("STUB: connect called\n"); }
void crc32() { printf("STUB: crc32 called\n"); }
void deflate() { printf("STUB: deflate called\n"); }
void deflateEnd() { printf("STUB: deflateEnd called\n"); }
void deflateInit2_() { printf("STUB: deflateInit2_ called\n"); }
void difftime() { printf("STUB: difftime called\n"); }
void div() { printf("STUB: div called\n"); }
void dl_iterate_phdr() { printf("STUB: dl_iterate_phdr called\n"); }
void dladdr() { printf("STUB: dladdr called\n"); }
void dup() { printf("STUB: dup called\n"); }
void dup2() { printf("STUB: dup2 called\n"); }
void eglChooseConfig() { printf("STUB: eglChooseConfig called\n"); }
void eglCreateContext() { printf("STUB: eglCreateContext called\n"); }
void eglCreatePbufferSurface() { printf("STUB: eglCreatePbufferSurface called\n"); }
void eglCreateWindowSurface() { printf("STUB: eglCreateWindowSurface called\n"); }
void eglDestroyContext() { printf("STUB: eglDestroyContext called\n"); }
void eglDestroySurface() { printf("STUB: eglDestroySurface called\n"); }
void eglGetConfigAttrib() { printf("STUB: eglGetConfigAttrib called\n"); }
void eglGetCurrentContext() { printf("STUB: eglGetCurrentContext called\n"); }
void eglGetCurrentSurface() { printf("STUB: eglGetCurrentSurface called\n"); }
void eglGetDisplay() { printf("STUB: eglGetDisplay called\n"); }
void eglGetError() { printf("STUB: eglGetError called\n"); }
void eglGetProcAddress() { printf("STUB: eglGetProcAddress called\n"); }
void eglInitialize() { printf("STUB: eglInitialize called\n"); }
void eglMakeCurrent() { printf("STUB: eglMakeCurrent called\n"); }
void eglQueryString() { printf("STUB: eglQueryString called\n"); }
void eglQuerySurface() { printf("STUB: eglQuerySurface called\n"); }
void eglSurfaceAttrib() { printf("STUB: eglSurfaceAttrib called\n"); }
void eglSwapBuffers() { printf("STUB: eglSwapBuffers called\n"); }
void eglSwapInterval() { printf("STUB: eglSwapInterval called\n"); }
void eglTerminate() { printf("STUB: eglTerminate called\n"); }
void environ() { printf("STUB: environ called\n"); }
void execl() { printf("STUB: execl called\n"); }
void fchmod() { printf("STUB: fchmod called\n"); }
void fcntl() { printf("STUB: fcntl called\n"); }
void flock() { printf("STUB: flock called\n"); }
void fnmatch() { printf("STUB: fnmatch called\n"); }
void fork() { printf("STUB: fork called\n"); }
void freeaddrinfo() { printf("STUB: freeaddrinfo called\n"); }
void freelocale() { printf("STUB: freelocale called\n"); }
void fstat() { printf("STUB: fstat called\n"); }
void ftruncate() { printf("STUB: ftruncate called\n"); }
void gai_strerror() { printf("STUB: gai_strerror called\n"); }
void getaddrinfo() { printf("STUB: getaddrinfo called\n"); }
void getcwd() { printf("STUB: getcwd called\n"); }
void getenv() { printf("STUB: getenv called\n"); }
void geteuid() { printf("STUB: geteuid called\n"); }
void gethostbyaddr() { printf("STUB: gethostbyaddr called\n"); }
void gethostbyname() { printf("STUB: gethostbyname called\n"); }
void gethostname() { printf("STUB: gethostname called\n"); }
void getnameinfo() { printf("STUB: getnameinfo called\n"); }
void getpagesize() { printf("STUB: getpagesize called\n"); }
void getpeername() { printf("STUB: getpeername called\n"); }
void getpid() { printf("STUB: getpid called\n"); }
void getpriority() { printf("STUB: getpriority called\n"); }
void getpwuid() { printf("STUB: getpwuid called\n"); }
void getpwuid_r() { printf("STUB: getpwuid_r called\n"); }
void getsockname() { printf("STUB: getsockname called\n"); }
void getsockopt() { printf("STUB: getsockopt called\n"); }
void gettid() { printf("STUB: gettid called\n"); }
void gettimeofday() { printf("STUB: gettimeofday called\n"); }
void getuid() { printf("STUB: getuid called\n"); }
void gmtime() { printf("STUB: gmtime called\n"); }
void gmtime_r() { printf("STUB: gmtime_r called\n"); }
void if_nametoindex() { printf("STUB: if_nametoindex called\n"); }
void inet_addr() { printf("STUB: inet_addr called\n"); }
void inet_ntop() { printf("STUB: inet_ntop called\n"); }
void inet_pton() { printf("STUB: inet_pton called\n"); }
void inflate() { printf("STUB: inflate called\n"); }
void inflateEnd() { printf("STUB: inflateEnd called\n"); }
void inflateInit2_() { printf("STUB: inflateInit2_ called\n"); }
void ioctl() { printf("STUB: ioctl called\n"); }
void isatty() { printf("STUB: isatty called\n"); }
void iswalpha() { printf("STUB: iswalpha called\n"); }
void iswblank() { printf("STUB: iswblank called\n"); }
void iswcntrl() { printf("STUB: iswcntrl called\n"); }
void iswdigit() { printf("STUB: iswdigit called\n"); }
void iswlower() { printf("STUB: iswlower called\n"); }
void iswprint() { printf("STUB: iswprint called\n"); }
void iswpunct() { printf("STUB: iswpunct called\n"); }
void iswspace() { printf("STUB: iswspace called\n"); }
void iswupper() { printf("STUB: iswupper called\n"); }
void iswxdigit() { printf("STUB: iswxdigit called\n"); }
void kill() { printf("STUB: kill called\n"); }
void listen() { printf("STUB: listen called\n"); }
void lldiv() { printf("STUB: lldiv called\n"); }
void localeconv() { printf("STUB: localeconv called\n"); }
void localtime() { printf("STUB: localtime called\n"); }
void localtime_r() { printf("STUB: localtime_r called\n"); }
void longjmp() { printf("STUB: longjmp called\n"); }
void lseek() { printf("STUB: lseek called\n"); }
void lseek64() { printf("STUB: lseek64 called\n"); }
void lstat() { printf("STUB: lstat called\n"); }
void madvise() { printf("STUB: madvise called\n"); }
void mbrlen() { printf("STUB: mbrlen called\n"); }
void mbrtowc() { printf("STUB: mbrtowc called\n"); }
void mbsnrtowcs() { printf("STUB: mbsnrtowcs called\n"); }
void mbsrtowcs() { printf("STUB: mbsrtowcs called\n"); }
void mbtowc() { printf("STUB: mbtowc called\n"); }
void memrchr() { printf("STUB: memrchr called\n"); }
void mkdir() { printf("STUB: mkdir called\n"); }
void mkstemp() { printf("STUB: mkstemp called\n"); }
void mktime() { printf("STUB: mktime called\n"); }
void mmap() { printf("STUB: mmap called\n"); }
void mprotect() { printf("STUB: mprotect called\n"); }
void munmap() { printf("STUB: munmap called\n"); }
void nanosleep() { printf("STUB: nanosleep called\n"); }
void newlocale() { printf("STUB: newlocale called\n"); }
void open() { printf("STUB: open called\n"); }
void opendir() { printf("STUB: opendir called\n"); }
void openlog() { printf("STUB: openlog called\n"); }
void pipe() { printf("STUB: pipe called\n"); }
void poll() { printf("STUB: poll called\n"); }
void posix_memalign() { printf("STUB: posix_memalign called\n"); }
void prctl() { printf("STUB: prctl called\n"); }
void pthread_atfork() { printf("STUB: pthread_atfork called\n"); }
void pthread_attr_destroy() { printf("STUB: pthread_attr_destroy called\n"); }
void pthread_attr_getstack() { printf("STUB: pthread_attr_getstack called\n"); }
void pthread_attr_init() { printf("STUB: pthread_attr_init called\n"); }
void pthread_attr_setdetachstate() { printf("STUB: pthread_attr_setdetachstate called\n"); }
void pthread_attr_setstacksize() { printf("STUB: pthread_attr_setstacksize called\n"); }
void pthread_cond_broadcast() { printf("STUB: pthread_cond_broadcast called\n"); }
void pthread_cond_destroy() { printf("STUB: pthread_cond_destroy called\n"); }
void pthread_cond_init() { printf("STUB: pthread_cond_init called\n"); }
void pthread_cond_signal() { printf("STUB: pthread_cond_signal called\n"); }
void pthread_cond_timedwait() { printf("STUB: pthread_cond_timedwait called\n"); }
void pthread_cond_wait() { printf("STUB: pthread_cond_wait called\n"); }
void pthread_condattr_destroy() { printf("STUB: pthread_condattr_destroy called\n"); }
void pthread_condattr_init() { printf("STUB: pthread_condattr_init called\n"); }
void pthread_condattr_setclock() { printf("STUB: pthread_condattr_setclock called\n"); }
void pthread_detach() { printf("STUB: pthread_detach called\n"); }
void pthread_equal() { printf("STUB: pthread_equal called\n"); }
void pthread_exit() { printf("STUB: pthread_exit called\n"); }
void pthread_getattr_np() { printf("STUB: pthread_getattr_np called\n"); }
void pthread_getspecific() { printf("STUB: pthread_getspecific called\n"); }
void pthread_key_create() { printf("STUB: pthread_key_create called\n"); }
void pthread_key_delete() { printf("STUB: pthread_key_delete called\n"); }
void pthread_kill() { printf("STUB: pthread_kill called\n"); }
void pthread_mutex_destroy() { printf("STUB: pthread_mutex_destroy called\n"); }
void pthread_mutex_init() { printf("STUB: pthread_mutex_init called\n"); }
void pthread_mutex_trylock() { printf("STUB: pthread_mutex_trylock called\n"); }
void pthread_mutexattr_destroy() { printf("STUB: pthread_mutexattr_destroy called\n"); }
void pthread_mutexattr_init() { printf("STUB: pthread_mutexattr_init called\n"); }
void pthread_mutexattr_settype() { printf("STUB: pthread_mutexattr_settype called\n"); }
void pthread_once() { printf("STUB: pthread_once called\n"); }
void pthread_rwlock_rdlock() { printf("STUB: pthread_rwlock_rdlock called\n"); }
void pthread_rwlock_unlock() { printf("STUB: pthread_rwlock_unlock called\n"); }
void pthread_rwlock_wrlock() { printf("STUB: pthread_rwlock_wrlock called\n"); }
void pthread_self() { printf("STUB: pthread_self called\n"); }
void pthread_setname_np() { printf("STUB: pthread_setname_np called\n"); }
void pthread_setschedparam() { printf("STUB: pthread_setschedparam called\n"); }
void pthread_setspecific() { printf("STUB: pthread_setspecific called\n"); }
void pthread_sigmask() { printf("STUB: pthread_sigmask called\n"); }
void qsort() { printf("STUB: qsort called\n"); }
void raise() { printf("STUB: raise called\n"); }
void rand() { printf("STUB: rand called\n"); }
void read() { printf("STUB: read called\n"); }
void readdir() { printf("STUB: readdir called\n"); }
void readlink() { printf("STUB: readlink called\n"); }
void realpath() { printf("STUB: realpath called\n"); }
void recv() { printf("STUB: recv called\n"); }
void recvfrom() { printf("STUB: recvfrom called\n"); }
void recvmsg() { printf("STUB: recvmsg called\n"); }
void rmdir() { printf("STUB: rmdir called\n"); }
void sched_get_priority_max() { printf("STUB: sched_get_priority_max called\n"); }
void sched_get_priority_min() { printf("STUB: sched_get_priority_min called\n"); }
void sched_getaffinity() { printf("STUB: sched_getaffinity called\n"); }
void sched_setaffinity() { printf("STUB: sched_setaffinity called\n"); }
void sched_yield() { printf("STUB: sched_yield called\n"); }
void select() { printf("STUB: select called\n"); }
void sem_destroy() { printf("STUB: sem_destroy called\n"); }
void sem_getvalue() { printf("STUB: sem_getvalue called\n"); }
void sem_init() { printf("STUB: sem_init called\n"); }
void sem_post() { printf("STUB: sem_post called\n"); }
void sem_timedwait() { printf("STUB: sem_timedwait called\n"); }
void sem_wait() { printf("STUB: sem_wait called\n"); }
void send() { printf("STUB: send called\n"); }
void sendmsg() { printf("STUB: sendmsg called\n"); }
void sendto() { printf("STUB: sendto called\n"); }
void setenv() { printf("STUB: setenv called\n"); }
void setjmp() { printf("STUB: setjmp called\n"); }
void setlocale() { printf("STUB: setlocale called\n"); }
void setpriority() { printf("STUB: setpriority called\n"); }
void setsockopt() { printf("STUB: setsockopt called\n"); }
void shutdown() { printf("STUB: shutdown called\n"); }
void sigaction() { printf("STUB: sigaction called\n"); }
void sigaddset() { printf("STUB: sigaddset called\n"); }
void sigaltstack() { printf("STUB: sigaltstack called\n"); }
void sigdelset() { printf("STUB: sigdelset called\n"); }
void sigemptyset() { printf("STUB: sigemptyset called\n"); }
void sigfillset() { printf("STUB: sigfillset called\n"); }
void signal() { printf("STUB: signal called\n"); }
void sigsuspend() { printf("STUB: sigsuspend called\n"); }
void sincos() { printf("STUB: sincos called\n"); }
void slCreateEngine() { printf("STUB: slCreateEngine called\n"); }
void socket() { printf("STUB: socket called\n"); }
void socketpair() { printf("STUB: socketpair called\n"); }
void stat() { printf("STUB: stat called\n"); }
void statfs() { printf("STUB: statfs called\n"); }
void strcoll() { printf("STUB: strcoll called\n"); }
void strerror_r() { printf("STUB: strerror_r called\n"); }
void strftime() { printf("STUB: strftime called\n"); }
void strnlen() { printf("STUB: strnlen called\n"); }
void strtok_r() { printf("STUB: strtok_r called\n"); }
void strtold_l() { printf("STUB: strtold_l called\n"); }
void strtoll_l() { printf("STUB: strtoll_l called\n"); }
void strtoull_l() { printf("STUB: strtoull_l called\n"); }
void swprintf() { printf("STUB: swprintf called\n"); }
void syscall() { printf("STUB: syscall called\n"); }
void sysconf() { printf("STUB: sysconf called\n"); }
void syslog() { printf("STUB: syslog called\n"); }
void tcflush() { printf("STUB: tcflush called\n"); }
void tcgetattr() { printf("STUB: tcgetattr called\n"); }
void tcsetattr() { printf("STUB: tcsetattr called\n"); }
void time() { printf("STUB: time called\n"); }
void towlower() { printf("STUB: towlower called\n"); }
void towupper() { printf("STUB: towupper called\n"); }
void truncate() { printf("STUB: truncate called\n"); }
void uname() { printf("STUB: uname called\n"); }
void unlink() { printf("STUB: unlink called\n"); }
void unsetenv() { printf("STUB: unsetenv called\n"); }
void uselocale() { printf("STUB: uselocale called\n"); }
void usleep() { printf("STUB: usleep called\n"); }
void utime() { printf("STUB: utime called\n"); }
void waitpid() { printf("STUB: waitpid called\n"); }
void wcrtomb() { printf("STUB: wcrtomb called\n"); }
void wcscoll() { printf("STUB: wcscoll called\n"); }
void wcsnrtombs() { printf("STUB: wcsnrtombs called\n"); }
void wcstod() { printf("STUB: wcstod called\n"); }
void wcstof() { printf("STUB: wcstof called\n"); }
void wcstol() { printf("STUB: wcstol called\n"); }
void wcstold() { printf("STUB: wcstold called\n"); }
void wcstoll() { printf("STUB: wcstoll called\n"); }
void wcstoul() { printf("STUB: wcstoul called\n"); }
void wcstoull() { printf("STUB: wcstoull called\n"); }
void wcsxfrm() { printf("STUB: wcsxfrm called\n"); }
void wctob() { printf("STUB: wctob called\n"); }
void wmemset() { printf("STUB: wmemset called\n"); }
void write() { printf("STUB: write called\n"); }
